import { generateId } from '@/lib/utils';

export interface Customer {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  address?: Address;
  dateOfBirth?: string;
  notes?: string;
  tags?: string[];
  totalSpent: number;
  totalOrders: number;
  membershipLevel?: string;
  loyaltyPoints: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Address {
  street: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  isDefault?: boolean;
}

// Generate mock customers
export const customers: Customer[] = [
  {
    id: generateId('cust_'),
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@example.com',
    phone: '555-123-4567',
    address: {
      street: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      postalCode: '12345',
      country: 'USA',
      isDefault: true,
    },
    dateOfBirth: new Date(1985, 5, 15).toISOString(),
    notes: 'Prefers email communication',
    tags: ['loyal', 'tech-enthusiast'],
    totalSpent: 2459.97,
    totalOrders: 7,
    membershipLevel: 'Gold',
    loyaltyPoints: 245,
    isActive: true,
    createdAt: new Date(2023, 2, 10).toISOString(),
    updatedAt: new Date(2024, 1, 5).toISOString(),
  },
  {
    id: generateId('cust_'),
    firstName: 'Emily',
    lastName: 'Johnson',
    email: 'emily.johnson@example.com',
    phone: '555-234-5678',
    address: {
      street: '456 Oak Ave',
      city: 'Somewhere',
      state: 'NY',
      postalCode: '67890',
      country: 'USA',
      isDefault: true,
    },
    dateOfBirth: new Date(1990, 8, 22).toISOString(),
    notes: 'Interested in home appliances',
    tags: ['new-customer'],
    totalSpent: 899.99,
    totalOrders: 2,
    membershipLevel: 'Silver',
    loyaltyPoints: 90,
    isActive: true,
    createdAt: new Date(2023, 11, 15).toISOString(),
    updatedAt: new Date(2024, 0, 20).toISOString(),
  },
  {
    id: generateId('cust_'),
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@example.com',
    phone: '555-345-6789',
    address: {
      street: '789 Pine St',
      city: 'Elsewhere',
      state: 'TX',
      postalCode: '54321',
      country: 'USA',
      isDefault: true,
    },
    dateOfBirth: new Date(1978, 3, 10).toISOString(),
    notes: 'Business customer, owns a small office',
    tags: ['business', 'office-supplies'],
    totalSpent: 5678.45,
    totalOrders: 12,
    membershipLevel: 'Platinum',
    loyaltyPoints: 568,
    isActive: true,
    createdAt: new Date(2022, 5, 20).toISOString(),
    updatedAt: new Date(2024, 1, 15).toISOString(),
  },
  {
    id: generateId('cust_'),
    firstName: 'Sarah',
    lastName: 'Davis',
    email: 'sarah.davis@example.com',
    phone: '555-456-7890',
    address: {
      street: '101 Maple Dr',
      city: 'Nowhere',
      state: 'FL',
      postalCode: '98765',
      country: 'USA',
      isDefault: true,
    },
    dateOfBirth: new Date(1992, 10, 5).toISOString(),
    notes: 'Prefers phone calls',
    tags: ['tech-enthusiast'],
    totalSpent: 1299.99,
    totalOrders: 3,
    membershipLevel: 'Silver',
    loyaltyPoints: 130,
    isActive: true,
    createdAt: new Date(2023, 8, 5).toISOString(),
    updatedAt: new Date(2023, 11, 10).toISOString(),
  },
  {
    id: generateId('cust_'),
    firstName: 'David',
    lastName: 'Wilson',
    email: 'david.wilson@example.com',
    phone: '555-567-8901',
    address: {
      street: '202 Cedar Ln',
      city: 'Someplace',
      state: 'WA',
      postalCode: '13579',
      country: 'USA',
      isDefault: true,
    },
    dateOfBirth: new Date(1982, 7, 30).toISOString(),
    notes: 'Interested in gaming products',
    tags: ['gamer', 'tech-enthusiast'],
    totalSpent: 3499.95,
    totalOrders: 8,
    membershipLevel: 'Gold',
    loyaltyPoints: 350,
    isActive: true,
    createdAt: new Date(2022, 9, 12).toISOString(),
    updatedAt: new Date(2024, 0, 5).toISOString(),
  },
  {
    id: generateId('cust_'),
    firstName: 'Jennifer',
    lastName: 'Martinez',
    email: 'jennifer.martinez@example.com',
    phone: '555-678-9012',
    address: {
      street: '303 Birch Rd',
      city: 'Anywhere',
      state: 'IL',
      postalCode: '24680',
      country: 'USA',
      isDefault: true,
    },
    dateOfBirth: new Date(1988, 1, 14).toISOString(),
    notes: 'Interior designer, interested in home products',
    tags: ['business', 'home-decor'],
    totalSpent: 4250.75,
    totalOrders: 9,
    membershipLevel: 'Gold',
    loyaltyPoints: 425,
    isActive: true,
    createdAt: new Date(2022, 11, 3).toISOString(),
    updatedAt: new Date(2024, 1, 28).toISOString(),
  },
  {
    id: generateId('cust_'),
    firstName: 'Robert',
    lastName: 'Taylor',
    email: 'robert.taylor@example.com',
    phone: '555-789-0123',
    address: {
      street: '404 Elm St',
      city: 'Otherville',
      state: 'GA',
      postalCode: '36925',
      country: 'USA',
      isDefault: true,
    },
    dateOfBirth: new Date(1975, 4, 20).toISOString(),
    notes: 'Prefers in-store pickup',
    tags: ['local'],
    totalSpent: 789.98,
    totalOrders: 4,
    membershipLevel: 'Bronze',
    loyaltyPoints: 80,
    isActive: true,
    createdAt: new Date(2023, 6, 18).toISOString(),
    updatedAt: new Date(2023, 10, 25).toISOString(),
  },
  {
    id: generateId('cust_'),
    firstName: 'Lisa',
    lastName: 'Anderson',
    email: 'lisa.anderson@example.com',
    phone: '555-890-1234',
    address: {
      street: '505 Walnut Ave',
      city: 'Sometown',
      state: 'MI',
      postalCode: '14703',
      country: 'USA',
      isDefault: true,
    },
    dateOfBirth: new Date(1995, 9, 8).toISOString(),
    notes: 'Student, price-conscious',
    tags: ['student', 'budget'],
    totalSpent: 349.97,
    totalOrders: 3,
    membershipLevel: 'Bronze',
    loyaltyPoints: 35,
    isActive: true,
    createdAt: new Date(2023, 9, 30).toISOString(),
    updatedAt: new Date(2024, 0, 15).toISOString(),
  },
  {
    id: generateId('cust_'),
    firstName: 'James',
    lastName: 'Thomas',
    email: 'james.thomas@example.com',
    phone: '555-901-2345',
    address: {
      street: '606 Cherry St',
      city: 'Anyplace',
      state: 'OH',
      postalCode: '25814',
      country: 'USA',
      isDefault: true,
    },
    dateOfBirth: new Date(1980, 2, 25).toISOString(),
    notes: 'Interested in audio equipment',
    tags: ['audiophile', 'tech-enthusiast'],
    totalSpent: 2199.97,
    totalOrders: 5,
    membershipLevel: 'Silver',
    loyaltyPoints: 220,
    isActive: true,
    createdAt: new Date(2023, 1, 8).toISOString(),
    updatedAt: new Date(2024, 1, 12).toISOString(),
  },
  {
    id: generateId('cust_'),
    firstName: 'Patricia',
    lastName: 'White',
    email: 'patricia.white@example.com',
    phone: '555-012-3456',
    address: {
      street: '707 Spruce Dr',
      city: 'Somewhere Else',
      state: 'AZ',
      postalCode: '36925',
      country: 'USA',
      isDefault: true,
    },
    dateOfBirth: new Date(1987, 11, 12).toISOString(),
    notes: 'Works from home, interested in office equipment',
    tags: ['home-office', 'business'],
    totalSpent: 1875.45,
    totalOrders: 6,
    membershipLevel: 'Silver',
    loyaltyPoints: 188,
    isActive: true,
    createdAt: new Date(2022, 8, 15).toISOString(),
    updatedAt: new Date(2023, 11, 20).toISOString(),
  },
];

export default customers;
