import { generateId } from '@/lib/utils';

export interface Product {
  id: string;
  name: string;
  description: string;
  sku: string;
  barcode?: string;
  price: number;
  cost: number;
  categoryId: string;
  taxRate: number;
  discountable: boolean;
  trackInventory: boolean;
  inventoryLevel?: number;
  reorderLevel?: number;
  images: string[];
  attributes: Record<string, string>;
  variants?: ProductVariant[];
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ProductVariant {
  id: string;
  productId: string;
  name: string;
  sku: string;
  barcode?: string;
  price: number;
  cost: number;
  inventoryLevel?: number;
  attributes: Record<string, string>;
  isActive: boolean;
}

// Generate mock products
export const products: Product[] = [
  {
    id: generateId('prod_'),
    name: 'Laptop Pro 15"',
    description: 'High-performance laptop with 15" display, 16GB RAM, and 512GB SSD',
    sku: 'LAP-PRO-15',
    barcode: '123456789012',
    price: 1299.99,
    cost: 899.99,
    categoryId: 'cat_electronics',
    taxRate: 8.5,
    discountable: true,
    trackInventory: true,
    inventoryLevel: 25,
    reorderLevel: 5,
    images: ['/images/products/laptop-pro-15.jpg'],
    attributes: {
      brand: 'TechMaster',
      color: 'Silver',
      processor: 'Intel i7',
      memory: '16GB',
      storage: '512GB SSD',
      display: '15.6" Retina',
      warranty: '2 years',
    },
    isActive: true,
    createdAt: new Date(2024, 0, 15).toISOString(),
    updatedAt: new Date(2024, 1, 20).toISOString(),
  },
  {
    id: generateId('prod_'),
    name: 'Smartphone X',
    description: 'Latest smartphone with 6.5" OLED display, 128GB storage, and triple camera',
    sku: 'PHONE-X-128',
    barcode: '234567890123',
    price: 899.99,
    cost: 599.99,
    categoryId: 'cat_electronics',
    taxRate: 8.5,
    discountable: true,
    trackInventory: true,
    inventoryLevel: 42,
    reorderLevel: 10,
    images: ['/images/products/smartphone-x.jpg'],
    attributes: {
      brand: 'MobileTech',
      color: 'Midnight Black',
      processor: 'Snapdragon 8 Gen 2',
      memory: '8GB',
      storage: '128GB',
      display: '6.5" OLED',
      camera: 'Triple 48MP + 12MP + 8MP',
      battery: '4500mAh',
      warranty: '1 year',
    },
    variants: [
      {
        id: generateId('var_'),
        productId: 'prod_smartphone_x',
        name: 'Smartphone X - 128GB - Midnight Black',
        sku: 'PHONE-X-128-BLK',
        barcode: '234567890124',
        price: 899.99,
        cost: 599.99,
        inventoryLevel: 15,
        attributes: {
          color: 'Midnight Black',
          storage: '128GB',
        },
        isActive: true,
      },
      {
        id: generateId('var_'),
        productId: 'prod_smartphone_x',
        name: 'Smartphone X - 128GB - Pearl White',
        sku: 'PHONE-X-128-WHT',
        barcode: '234567890125',
        price: 899.99,
        cost: 599.99,
        inventoryLevel: 12,
        attributes: {
          color: 'Pearl White',
          storage: '128GB',
        },
        isActive: true,
      },
      {
        id: generateId('var_'),
        productId: 'prod_smartphone_x',
        name: 'Smartphone X - 256GB - Midnight Black',
        sku: 'PHONE-X-256-BLK',
        barcode: '234567890126',
        price: 999.99,
        cost: 699.99,
        inventoryLevel: 8,
        attributes: {
          color: 'Midnight Black',
          storage: '256GB',
        },
        isActive: true,
      },
      {
        id: generateId('var_'),
        productId: 'prod_smartphone_x',
        name: 'Smartphone X - 256GB - Pearl White',
        sku: 'PHONE-X-256-WHT',
        barcode: '234567890127',
        price: 999.99,
        cost: 699.99,
        inventoryLevel: 7,
        attributes: {
          color: 'Pearl White',
          storage: '256GB',
        },
        isActive: true,
      },
    ],
    isActive: true,
    createdAt: new Date(2024, 1, 5).toISOString(),
    updatedAt: new Date(2024, 2, 1).toISOString(),
  },
  {
    id: generateId('prod_'),
    name: 'Wireless Earbuds Pro',
    description: 'Premium wireless earbuds with noise cancellation and 24-hour battery life',
    sku: 'AUDIO-EB-PRO',
    barcode: '345678901234',
    price: 149.99,
    cost: 79.99,
    categoryId: 'cat_electronics',
    taxRate: 8.5,
    discountable: true,
    trackInventory: true,
    inventoryLevel: 60,
    reorderLevel: 15,
    images: ['/images/products/wireless-earbuds.jpg'],
    attributes: {
      brand: 'AudioTech',
      color: 'Black',
      batteryLife: '24 hours',
      noiseReduction: 'Active',
      waterResistant: 'IPX4',
      warranty: '1 year',
    },
    isActive: true,
    createdAt: new Date(2024, 0, 20).toISOString(),
    updatedAt: new Date(2024, 0, 20).toISOString(),
  },
  {
    id: generateId('prod_'),
    name: 'Coffee Maker Deluxe',
    description: 'Programmable coffee maker with 12-cup capacity and built-in grinder',
    sku: 'HOME-CM-DLX',
    barcode: '456789012345',
    price: 129.99,
    cost: 69.99,
    categoryId: 'cat_home_appliances',
    taxRate: 7.0,
    discountable: true,
    trackInventory: true,
    inventoryLevel: 35,
    reorderLevel: 8,
    images: ['/images/products/coffee-maker.jpg'],
    attributes: {
      brand: 'HomeComfort',
      color: 'Stainless Steel',
      capacity: '12 cups',
      programmable: 'Yes',
      builtInGrinder: 'Yes',
      warranty: '2 years',
    },
    isActive: true,
    createdAt: new Date(2023, 11, 10).toISOString(),
    updatedAt: new Date(2024, 1, 15).toISOString(),
  },
  {
    id: generateId('prod_'),
    name: 'Fitness Tracker Watch',
    description: 'Advanced fitness tracker with heart rate monitor, GPS, and sleep tracking',
    sku: 'WEAR-FT-PRO',
    barcode: '567890123456',
    price: 89.99,
    cost: 39.99,
    categoryId: 'cat_wearables',
    taxRate: 8.5,
    discountable: true,
    trackInventory: true,
    inventoryLevel: 48,
    reorderLevel: 12,
    images: ['/images/products/fitness-tracker.jpg'],
    attributes: {
      brand: 'FitTech',
      color: 'Black',
      display: 'OLED',
      heartRateMonitor: 'Yes',
      gps: 'Yes',
      waterResistant: '50m',
      batteryLife: '7 days',
      warranty: '1 year',
    },
    variants: [
      {
        id: generateId('var_'),
        productId: 'prod_fitness_tracker',
        name: 'Fitness Tracker Watch - Black',
        sku: 'WEAR-FT-PRO-BLK',
        barcode: '567890123457',
        price: 89.99,
        cost: 39.99,
        inventoryLevel: 20,
        attributes: {
          color: 'Black',
        },
        isActive: true,
      },
      {
        id: generateId('var_'),
        productId: 'prod_fitness_tracker',
        name: 'Fitness Tracker Watch - Blue',
        sku: 'WEAR-FT-PRO-BLU',
        barcode: '567890123458',
        price: 89.99,
        cost: 39.99,
        inventoryLevel: 15,
        attributes: {
          color: 'Blue',
        },
        isActive: true,
      },
      {
        id: generateId('var_'),
        productId: 'prod_fitness_tracker',
        name: 'Fitness Tracker Watch - Pink',
        sku: 'WEAR-FT-PRO-PNK',
        barcode: '567890123459',
        price: 89.99,
        cost: 39.99,
        inventoryLevel: 13,
        attributes: {
          color: 'Pink',
        },
        isActive: true,
      },
    ],
    isActive: true,
    createdAt: new Date(2024, 0, 5).toISOString(),
    updatedAt: new Date(2024, 0, 5).toISOString(),
  },
  {
    id: generateId('prod_'),
    name: 'Gaming Console Pro',
    description: 'Next-generation gaming console with 1TB storage and 4K gaming',
    sku: 'GAME-CONS-PRO',
    barcode: '678901234567',
    price: 499.99,
    cost: 349.99,
    categoryId: 'cat_electronics',
    taxRate: 8.5,
    discountable: false,
    trackInventory: true,
    inventoryLevel: 15,
    reorderLevel: 5,
    images: ['/images/products/gaming-console.jpg'],
    attributes: {
      brand: 'GameMaster',
      color: 'Black',
      storage: '1TB SSD',
      resolution: '4K',
      hdmiPorts: '2',
      usbPorts: '3',
      warranty: '2 years',
    },
    isActive: true,
    createdAt: new Date(2024, 1, 10).toISOString(),
    updatedAt: new Date(2024, 1, 10).toISOString(),
  },
  {
    id: generateId('prod_'),
    name: 'Smart LED TV 55"',
    description: '55-inch 4K Smart LED TV with HDR and built-in streaming apps',
    sku: 'TV-LED-55',
    barcode: '789012345678',
    price: 599.99,
    cost: 399.99,
    categoryId: 'cat_electronics',
    taxRate: 8.5,
    discountable: true,
    trackInventory: true,
    inventoryLevel: 20,
    reorderLevel: 5,
    images: ['/images/products/smart-tv.jpg'],
    attributes: {
      brand: 'VisionTech',
      size: '55"',
      resolution: '4K Ultra HD',
      hdr: 'Yes',
      smartFeatures: 'Yes',
      hdmiPorts: '4',
      usbPorts: '2',
      warranty: '3 years',
    },
    isActive: true,
    createdAt: new Date(2023, 10, 20).toISOString(),
    updatedAt: new Date(2024, 1, 5).toISOString(),
  },
  {
    id: generateId('prod_'),
    name: 'Bluetooth Speaker Portable',
    description: 'Waterproof portable Bluetooth speaker with 20-hour battery life',
    sku: 'AUDIO-BT-SPK',
    barcode: '890123456789',
    price: 79.99,
    cost: 39.99,
    categoryId: 'cat_electronics',
    taxRate: 8.5,
    discountable: true,
    trackInventory: true,
    inventoryLevel: 45,
    reorderLevel: 10,
    images: ['/images/products/bluetooth-speaker.jpg'],
    attributes: {
      brand: 'AudioTech',
      color: 'Black',
      batteryLife: '20 hours',
      waterproof: 'IPX7',
      bluetoothVersion: '5.0',
      warranty: '1 year',
    },
    variants: [
      {
        id: generateId('var_'),
        productId: 'prod_bluetooth_speaker',
        name: 'Bluetooth Speaker Portable - Black',
        sku: 'AUDIO-BT-SPK-BLK',
        barcode: '890123456790',
        price: 79.99,
        cost: 39.99,
        inventoryLevel: 20,
        attributes: {
          color: 'Black',
        },
        isActive: true,
      },
      {
        id: generateId('var_'),
        productId: 'prod_bluetooth_speaker',
        name: 'Bluetooth Speaker Portable - Blue',
        sku: 'AUDIO-BT-SPK-BLU',
        barcode: '890123456791',
        price: 79.99,
        cost: 39.99,
        inventoryLevel: 15,
        attributes: {
          color: 'Blue',
        },
        isActive: true,
      },
      {
        id: generateId('var_'),
        productId: 'prod_bluetooth_speaker',
        name: 'Bluetooth Speaker Portable - Red',
        sku: 'AUDIO-BT-SPK-RED',
        barcode: '890123456792',
        price: 79.99,
        cost: 39.99,
        inventoryLevel: 10,
        attributes: {
          color: 'Red',
        },
        isActive: true,
      },
    ],
    isActive: true,
    createdAt: new Date(2023, 11, 15).toISOString(),
    updatedAt: new Date(2023, 11, 15).toISOString(),
  },
  {
    id: generateId('prod_'),
    name: 'Digital Camera Pro',
    description: 'Professional digital camera with 24MP sensor and 4K video recording',
    sku: 'PHOTO-CAM-PRO',
    barcode: '901234567890',
    price: 799.99,
    cost: 499.99,
    categoryId: 'cat_electronics',
    taxRate: 8.5,
    discountable: true,
    trackInventory: true,
    inventoryLevel: 18,
    reorderLevel: 5,
    images: ['/images/products/digital-camera.jpg'],
    attributes: {
      brand: 'CaptureTech',
      color: 'Black',
      sensorType: 'CMOS',
      megapixels: '24MP',
      videoResolution: '4K',
      opticalZoom: '5x',
      storage: 'SD Card',
      warranty: '2 years',
    },
    isActive: true,
    createdAt: new Date(2024, 0, 10).toISOString(),
    updatedAt: new Date(2024, 0, 10).toISOString(),
  },
  {
    id: generateId('prod_'),
    name: 'Desk Chair Ergonomic',
    description: 'Ergonomic office chair with adjustable height, lumbar support, and armrests',
    sku: 'FURN-CHAIR-ERG',
    barcode: '012345678901',
    price: 199.99,
    cost: 119.99,
    categoryId: 'cat_furniture',
    taxRate: 7.0,
    discountable: true,
    trackInventory: true,
    inventoryLevel: 25,
    reorderLevel: 5,
    images: ['/images/products/desk-chair.jpg'],
    attributes: {
      brand: 'ComfortOffice',
      color: 'Black',
      material: 'Mesh and Leather',
      adjustableHeight: 'Yes',
      lumbarSupport: 'Yes',
      armrests: 'Adjustable',
      maxWeight: '300 lbs',
      warranty: '5 years',
    },
    isActive: true,
    createdAt: new Date(2023, 9, 5).toISOString(),
    updatedAt: new Date(2024, 1, 20).toISOString(),
  },
];

export default products;
