import { generateId } from '@/lib/utils';
import { Address } from './customers';

export interface Supplier {
  id: string;
  name: string;
  contactPerson: string;
  email: string;
  phone: string;
  address: Address;
  taxId?: string;
  website?: string;
  notes?: string;
  paymentTerms?: string;
  accountNumber?: string;
  categories: string[];
  rating?: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// Generate mock suppliers
export const suppliers: Supplier[] = [
  {
    id: generateId('supp_'),
    name: 'TechMaster Electronics',
    contactPerson: 'Richard Chen',
    email: 'richard.chen@techmaster.com',
    phone: '555-111-2222',
    address: {
      street: '123 Tech Blvd',
      city: 'San Jose',
      state: 'CA',
      postalCode: '95123',
      country: 'USA',
      isDefault: true,
    },
    taxId: '12-3456789',
    website: 'https://www.techmasterelectronics.com',
    notes: 'Reliable supplier for laptops and computer accessories',
    paymentTerms: 'Net 30',
    accountNumber: 'TM-12345',
    categories: ['cat_electronics', 'cat_computers'],
    rating: 4.8,
    isActive: true,
    createdAt: new Date(2022, 0, 15).toISOString(),
    updatedAt: new Date(2023, 11, 10).toISOString(),
  },
  {
    id: generateId('supp_'),
    name: 'MobileTech Distributors',
    contactPerson: 'Sarah Johnson',
    email: 'sarah.johnson@mobiletech.com',
    phone: '555-222-3333',
    address: {
      street: '456 Mobile Way',
      city: 'Austin',
      state: 'TX',
      postalCode: '78701',
      country: 'USA',
      isDefault: true,
    },
    taxId: '23-4567890',
    website: 'https://www.mobiletechdist.com',
    notes: 'Specializes in smartphones and tablets',
    paymentTerms: 'Net 45',
    accountNumber: 'MT-23456',
    categories: ['cat_electronics', 'cat_phones'],
    rating: 4.5,
    isActive: true,
    createdAt: new Date(2022, 2, 20).toISOString(),
    updatedAt: new Date(2024, 0, 15).toISOString(),
  },
  {
    id: generateId('supp_'),
    name: 'AudioTech Solutions',
    contactPerson: 'Michael Brown',
    email: 'michael.brown@audiotech.com',
    phone: '555-333-4444',
    address: {
      street: '789 Sound Ave',
      city: 'Nashville',
      state: 'TN',
      postalCode: '37203',
      country: 'USA',
      isDefault: true,
    },
    taxId: '34-5678901',
    website: 'https://www.audiotechsolutions.com',
    notes: 'Premium audio equipment supplier',
    paymentTerms: 'Net 30',
    accountNumber: 'AT-34567',
    categories: ['cat_electronics', 'cat_audio'],
    rating: 4.7,
    isActive: true,
    createdAt: new Date(2022, 4, 10).toISOString(),
    updatedAt: new Date(2023, 10, 5).toISOString(),
  },
  {
    id: generateId('supp_'),
    name: 'HomeComfort Appliances',
    contactPerson: 'Jennifer Davis',
    email: 'jennifer.davis@homecomfort.com',
    phone: '555-444-5555',
    address: {
      street: '101 Appliance Dr',
      city: 'Chicago',
      state: 'IL',
      postalCode: '60607',
      country: 'USA',
      isDefault: true,
    },
    taxId: '45-6789012',
    website: 'https://www.homecomfortappliances.com',
    notes: 'Home and kitchen appliance wholesaler',
    paymentTerms: 'Net 60',
    accountNumber: 'HC-45678',
    categories: ['cat_home_appliances', 'cat_kitchen'],
    rating: 4.3,
    isActive: true,
    createdAt: new Date(2022, 6, 15).toISOString(),
    updatedAt: new Date(2024, 1, 20).toISOString(),
  },
  {
    id: generateId('supp_'),
    name: 'FitTech Wearables',
    contactPerson: 'David Wilson',
    email: 'david.wilson@fittech.com',
    phone: '555-555-6666',
    address: {
      street: '202 Fitness Blvd',
      city: 'Portland',
      state: 'OR',
      postalCode: '97205',
      country: 'USA',
      isDefault: true,
    },
    taxId: '56-7890123',
    website: 'https://www.fittechgear.com',
    notes: 'Specializes in fitness trackers and smartwatches',
    paymentTerms: 'Net 30',
    accountNumber: 'FT-56789',
    categories: ['cat_electronics', 'cat_wearables'],
    rating: 4.6,
    isActive: true,
    createdAt: new Date(2022, 8, 5).toISOString(),
    updatedAt: new Date(2023, 9, 15).toISOString(),
  },
  {
    id: generateId('supp_'),
    name: 'GameMaster Entertainment',
    contactPerson: 'Robert Taylor',
    email: 'robert.taylor@gamemaster.com',
    phone: '555-666-7777',
    address: {
      street: '303 Gaming Way',
      city: 'Seattle',
      state: 'WA',
      postalCode: '98101',
      country: 'USA',
      isDefault: true,
    },
    taxId: '67-8901234',
    website: 'https://www.gamemasterent.com',
    notes: 'Gaming consoles and accessories supplier',
    paymentTerms: 'Net 45',
    accountNumber: 'GM-67890',
    categories: ['cat_electronics'],
    rating: 4.4,
    isActive: true,
    createdAt: new Date(2022, 10, 10).toISOString(),
    updatedAt: new Date(2024, 0, 5).toISOString(),
  },
  {
    id: generateId('supp_'),
    name: 'VisionTech Displays',
    contactPerson: 'Lisa Martinez',
    email: 'lisa.martinez@visiontech.com',
    phone: '555-777-8888',
    address: {
      street: '404 Display Rd',
      city: 'Denver',
      state: 'CO',
      postalCode: '80202',
      country: 'USA',
      isDefault: true,
    },
    taxId: '78-9012345',
    website: 'https://www.visiontechdisplays.com',
    notes: 'TV and monitor supplier',
    paymentTerms: 'Net 30',
    accountNumber: 'VT-78901',
    categories: ['cat_electronics'],
    rating: 4.2,
    isActive: true,
    createdAt: new Date(2023, 0, 20).toISOString(),
    updatedAt: new Date(2023, 11, 15).toISOString(),
  },
  {
    id: generateId('supp_'),
    name: 'CaptureTech Imaging',
    contactPerson: 'James Anderson',
    email: 'james.anderson@capturetech.com',
    phone: '555-888-9999',
    address: {
      street: '505 Camera St',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      country: 'USA',
      isDefault: true,
    },
    taxId: '89-0123456',
    website: 'https://www.capturetechimaging.com',
    notes: 'Camera and photography equipment supplier',
    paymentTerms: 'Net 45',
    accountNumber: 'CT-89012',
    categories: ['cat_electronics'],
    rating: 4.5,
    isActive: true,
    createdAt: new Date(2023, 2, 15).toISOString(),
    updatedAt: new Date(2024, 1, 10).toISOString(),
  },
  {
    id: generateId('supp_'),
    name: 'ComfortOffice Furniture',
    contactPerson: 'Patricia Thomas',
    email: 'patricia.thomas@comfortoffice.com',
    phone: '555-999-0000',
    address: {
      street: '606 Office Park',
      city: 'Atlanta',
      state: 'GA',
      postalCode: '30303',
      country: 'USA',
      isDefault: true,
    },
    taxId: '90-1234567',
    website: 'https://www.comfortofficefurniture.com',
    notes: 'Office furniture and ergonomic solutions',
    paymentTerms: 'Net 60',
    accountNumber: 'CO-90123',
    categories: ['cat_furniture', 'cat_office_furniture'],
    rating: 4.1,
    isActive: true,
    createdAt: new Date(2023, 4, 5).toISOString(),
    updatedAt: new Date(2023, 9, 20).toISOString(),
  },
  {
    id: generateId('supp_'),
    name: 'CleanTech Solutions',
    contactPerson: 'Mark Williams',
    email: 'mark.williams@cleantech.com',
    phone: '555-000-1111',
    address: {
      street: '707 Cleaning Ave',
      city: 'Boston',
      state: 'MA',
      postalCode: '02108',
      country: 'USA',
      isDefault: true,
    },
    taxId: '01-2345678',
    website: 'https://www.cleantechsolutions.com',
    notes: 'Cleaning appliances and equipment',
    paymentTerms: 'Net 30',
    accountNumber: 'CL-01234',
    categories: ['cat_home_appliances', 'cat_cleaning'],
    rating: 4.0,
    isActive: true,
    createdAt: new Date(2023, 6, 10).toISOString(),
    updatedAt: new Date(2024, 0, 25).toISOString(),
  },
];

export default suppliers;
