import { GiftCard, GiftCardTransaction, DesignTemplate, GiftCardStatus } from '../types';

// Helper to generate random gift card codes
const generateCardCode = () => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  for (let i = 0; i < 16; i++) {
    if (i > 0 && i % 4 === 0) result += '-';
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};

// Helper to generate past or future dates
const generateDate = (daysOffset: number) => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date;
};

// Mock gift card data
export const mockGiftCards: GiftCard[] = [
  {
    id: '1',
    code: 'GIFT-ABCD-1234-EFGH',
    initialValue: 50.00,
    balance: 50.00,
    expirationDate: generateDate(90),
    issueDate: generateDate(-5),
    lastUsedDate: null,
    status: 'active',
    recipient: {
      name: 'John Doe',
      email: 'john.doe@example.com',
    },
    sender: {
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
    },
    message: 'Happy Birthday! Enjoy your gift.',
    designTemplateId: '1',
    metadata: {},
  },
  {
    id: '2',
    code: 'GIFT-WXYZ-5678-IJKL',
    initialValue: 100.00,
    balance: 75.50,
    expirationDate: generateDate(120),
    issueDate: generateDate(-30),
    lastUsedDate: generateDate(-10),
    status: 'active',
    recipient: {
      name: 'Alice Johnson',
      email: 'alice@example.com',
    },
    sender: {
      name: 'Bob Williams',
      email: 'bob@example.com',
    },
    message: 'Thank you for your help!',
    designTemplateId: '2',
    metadata: {},
  },
  {
    id: '3',
    code: 'GIFT-MNOP-9012-QRST',
    initialValue: 25.00,
    balance: 0,
    expirationDate: generateDate(60),
    issueDate: generateDate(-45),
    lastUsedDate: generateDate(-2),
    status: 'used',
    recipient: {
      name: 'Charlie Brown',
      email: 'charlie@example.com',
    },
    sender: {
      name: 'Lucy van Pelt',
      email: 'lucy@example.com',
    },
    message: 'For your collection.',
    designTemplateId: '3',
    metadata: {},
  },
  {
    id: '4',
    code: 'GIFT-UVWX-3456-YZ12',
    initialValue: 200.00,
    balance: 200.00,
    expirationDate: null, // Never expires
    issueDate: generateDate(-1),
    lastUsedDate: null,
    status: 'active',
    recipient: {
      name: 'David Miller',
      email: 'david@example.com',
    },
    sender: {
      name: 'Emma Wilson',
      email: 'emma@example.com',
    },
    message: 'Congratulations on your new home!',
    designTemplateId: '4',
    metadata: {},
  },
  {
    id: '5',
    code: 'GIFT-7890-ABCD-EFGH',
    initialValue: 75.00,
    balance: 0,
    expirationDate: generateDate(-30),
    issueDate: generateDate(-120),
    lastUsedDate: null,
    status: 'expired',
    recipient: {
      name: 'Frank Johnson',
      email: 'frank@example.com',
    },
    sender: {
      name: 'Grace Lee',
      email: 'grace@example.com',
    },
    message: 'Happy Holidays!',
    designTemplateId: '5',
    metadata: {},
  },
  {
    id: '6',
    code: 'GIFT-IJKL-1234-MNOP',
    initialValue: 150.00,
    balance: 150.00,
    expirationDate: generateDate(180),
    issueDate: generateDate(-2),
    lastUsedDate: null,
    status: 'active',
    recipient: {
      name: 'Helen Davis',
      email: 'helen@example.com',
    },
    sender: {
      name: 'Ivan Rogers',
      email: 'ivan@example.com',
    },
    message: 'For your birthday. Enjoy!',
    designTemplateId: '1',
    metadata: {},
  },
  {
    id: '7',
    code: 'GIFT-QRST-5678-UVWX',
    initialValue: 50.00,
    balance: 0,
    expirationDate: generateDate(90),
    issueDate: generateDate(-15),
    lastUsedDate: generateDate(-5),
    status: 'used',
    recipient: {
      name: 'Jack Smith',
      email: 'jack@example.com',
    },
    sender: {
      name: 'Kelly Brown',
      email: 'kelly@example.com',
    },
    message: 'Thank you for your business.',
    designTemplateId: '2',
    metadata: {},
  },
  {
    id: '8',
    code: 'GIFT-YZ12-9012-3456',
    initialValue: 100.00,
    balance: 32.75,
    expirationDate: generateDate(60),
    issueDate: generateDate(-60),
    lastUsedDate: generateDate(-30),
    status: 'active',
    recipient: {
      name: 'Liam Wilson',
      email: 'liam@example.com',
    },
    sender: {
      name: 'Mia Thomas',
      email: 'mia@example.com',
    },
    message: 'Happy Anniversary!',
    designTemplateId: '3',
    metadata: {},
  },
];

// Mock transaction history
export const mockTransactions: GiftCardTransaction[] = [
  {
    id: '1',
    giftCardId: '2',
    type: 'issue',
    amount: 100.00,
    date: generateDate(-30),
    notes: 'Initial issue',
    performedBy: 'staff-001',
    balanceAfter: 100.00,
  },
  {
    id: '2',
    giftCardId: '2',
    type: 'redeem',
    amount: 24.50,
    date: generateDate(-10),
    notes: 'Purchase at Store #1234',
    performedBy: 'staff-002',
    balanceAfter: 75.50,
    orderId: 'order-001',
  },
  {
    id: '3',
    giftCardId: '3',
    type: 'issue',
    amount: 25.00,
    date: generateDate(-45),
    notes: 'Initial issue',
    performedBy: 'staff-001',
    balanceAfter: 25.00,
  },
  {
    id: '4',
    giftCardId: '3',
    type: 'redeem',
    amount: 25.00,
    date: generateDate(-2),
    notes: 'Full redemption',
    performedBy: 'staff-003',
    balanceAfter: 0.00,
    orderId: 'order-002',
  },
  {
    id: '5',
    giftCardId: '5',
    type: 'issue',
    amount: 75.00,
    date: generateDate(-120),
    notes: 'Initial issue',
    performedBy: 'staff-002',
    balanceAfter: 75.00,
  },
  {
    id: '6',
    giftCardId: '5',
    type: 'expire',
    amount: 75.00,
    date: generateDate(-30),
    notes: 'Card expired',
    performedBy: 'system',
    balanceAfter: 0.00,
  },
  {
    id: '7',
    giftCardId: '8',
    type: 'issue',
    amount: 100.00,
    date: generateDate(-60),
    notes: 'Initial issue',
    performedBy: 'staff-001',
    balanceAfter: 100.00,
  },
  {
    id: '8',
    giftCardId: '8',
    type: 'redeem',
    amount: 67.25,
    date: generateDate(-30),
    notes: 'Partial redemption',
    performedBy: 'staff-004',
    balanceAfter: 32.75,
    orderId: 'order-003',
  },
];

// Mock design templates
export const mockDesignTemplates: DesignTemplate[] = [
  {
    id: '1',
    name: 'Birthday Celebration',
    description: 'Colorful birthday theme with balloons and confetti',
    category: 'occasion',
    occasion: 'birthday',
    isActive: true,
    isDefault: false,
    version: '1.0',
    thumbnail: '/assets/gift-cards/templates/birthday-thumb.jpg',
    elements: [],
    styles: {
      backgroundColor: '#ffffff',
      backgroundImage: '/assets/gift-cards/templates/birthday-bg.jpg',
      width: 600,
      height: 300,
    },
    createdAt: generateDate(-90),
    updatedAt: generateDate(-90),
    createdBy: 'admin',
  },
  {
    id: '2',
    name: 'Thank You',
    description: 'Elegant thank you design with floral elements',
    category: 'occasion',
    occasion: 'thank you',
    isActive: true,
    isDefault: false,
    version: '1.0',
    thumbnail: '/assets/gift-cards/templates/thankyou-thumb.jpg',
    elements: [],
    styles: {
      backgroundColor: '#f5f5f5',
      backgroundImage: '/assets/gift-cards/templates/thankyou-bg.jpg',
      width: 600,
      height: 300,
    },
    createdAt: generateDate(-85),
    updatedAt: generateDate(-85),
    createdBy: 'admin',
  },
  {
    id: '3',
    name: 'Congratulations',
    description: 'Celebratory congratulations design',
    category: 'occasion',
    occasion: 'congratulations',
    isActive: true,
    isDefault: false,
    version: '1.0',
    thumbnail: '/assets/gift-cards/templates/congrats-thumb.jpg',
    elements: [],
    styles: {
      backgroundColor: '#e8f4f8',
      backgroundImage: '/assets/gift-cards/templates/congrats-bg.jpg',
      width: 600,
      height: 300,
    },
    createdAt: generateDate(-80),
    updatedAt: generateDate(-80),
    createdBy: 'admin',
  },
  {
    id: '4',
    name: 'Classic Design',
    description: 'Simple, elegant design for any occasion',
    category: 'default',
    isActive: true,
    isDefault: true,
    version: '1.0',
    thumbnail: '/assets/gift-cards/templates/classic-thumb.jpg',
    elements: [],
    styles: {
      backgroundColor: '#ffffff',
      backgroundImage: '/assets/gift-cards/templates/classic-bg.jpg',
      width: 600,
      height: 300,
    },
    createdAt: generateDate(-75),
    updatedAt: generateDate(-75),
    createdBy: 'admin',
  },
  {
    id: '5',
    name: 'Holiday Season',
    description: 'Festive holiday design with winter theme',
    category: 'seasonal',
    season: 'winter holidays',
    isActive: true,
    isDefault: false,
    version: '1.0',
    thumbnail: '/assets/gift-cards/templates/holiday-thumb.jpg',
    elements: [],
    styles: {
      backgroundColor: '#f0f8ff',
      backgroundImage: '/assets/gift-cards/templates/holiday-bg.jpg',
      width: 600,
      height: 300,
    },
    createdAt: generateDate(-70),
    updatedAt: generateDate(-70),
    createdBy: 'admin',
  },
]; 